### ISSUE TITLE
grouping in R

### ISSUE THREAD

**Issue by JillAshey** [Putnam-Lab/Lab_Management#12]
I'm looking at a NOAA dataset for water temperature in Newport, RI. the data has an observation taken every day every 6 minutes for the entirety of 2013. 

| Year | MM | DD | hh | mm | Temp |
|:---- |:------:| -----|:---- |:------:| -----:|
| 2013  | Jan    | 1 | 3 | 6 | 5 
| 2013  | Jan    | 1 | 3 | 12 | 5 
| 2013  | Jan    | 1 | 3 | 24| 5 

Year = 2013
MM = month
DD = day
mm = minutes
Temp = water temperature in degrees C

I want to make a 'week' column that groups 'DD' (corresponding to day) every 7 days into a week observation. The DD column has multiple observations per day. An abbreviated version of my desired table looks like this: 

| Year | MM | DD | hh | mm | Temp | Week |
|:---- |:------:| -----|:---- |:------:| -----:| -----:|
| 2013  | Jan    | 1 | 3 | 6 | 5 | week1
| 2013  | Jan    | 1 | 3 | 12 | 5 | week1
| 2013  | Jan    | 2 | 1 | 6| 4.5 | week1
| 2013  | Jan    | 2 | 1 | 12| 4.7 | week1
| 2013  | Jan    | 3 | 1 | 6| 4 | week1
| 2013  | Jan    | 3 | 1 | 12| 4.5 | week1
| 2013  | Jan    | 4 | 1 | 6| 4.5 | week1
| 2013  | Jan    | 4 | 1 | 12| 4.8 | week1
| 2013  | Jan    | 5 | 1 | 6| 4 | week1
| 2013  | Jan    | 5 | 1 | 12| 3.9 | week1
| 2013  | Jan    | 6 | 1 | 6| 4| week1
| 2013  | Jan    | 6 | 1 | 12| 4.5 | week1
| 2013  | Jan    | 7 | 1 | 6| 4 | week1
| 2013  | Jan    | 7 | 1 | 12| 4 | week1
| 2013  | Jan    | 8 | 1 | 6| 3.6 | week2
| 2013  | Jan    | 8 | 1 | 12| 3.7 | week2
| 2013  | Jan    | 9 | 1 | 6| 4 | week2
| 2013  | Jan    | 9 | 1 | 12| 4.3 | week2

and so on for the entire year. 

So far, I've tried: 

        newport2013$week <- c(0, rep(1:(nrow(newport2013)-1)%/%7))

but this just separated it into weeks by rows (ie first 7 rows were week1, next seven rows were week2). 

Also have tried the group_by function: 

        newport2013 <- newport2013$week %>% group_by(DD)

Any help would be greatly appreciated!!!!!

**Comment by daniellembecker** [comment]
I have not yet done this specifically, but for the large temp data sets I have used, this is a very helpful resource:

https://www.earthdatascience.org/courses/earth-analytics/time-series-data/subset-time-series-data-in-r/

**Comment by daniellembecker** [comment]
This also seems helpful:

https://stackoverflow.com/questions/29039656/convert-daily-data-into-weekly-in-r-week-starts-on-saturday

**Comment by daniellembecker** [comment]
https://www.r-bloggers.com/2013/08/plot-weekly-or-monthly-totals-in-r/

**Comment by JillAshey** [comment]
issue closed
