### ISSUE TITLE
Multiple PCA plots from one prcomp analysis 

### ISSUE THREAD

**Issue by emmastrand** [Putnam-Lab/Lab_Management#14]
I have the below plot (3x2 grid), but I did the analysis for each plot separately (hence the different % values on the axes). If I do all of M.cap in one analysis (see prcomp code below), how could I subset the phases to visualize separately? This way the axis values would be comparable between the 3 plots for each spp. The dataframe Mcap_timeseriesdata has a column with three phases: Acute, Chronic, Recovery. Is there a way I can compare the dataframe to the prcomp resulting dataframe to only take a certain phase in order to plot?

`Mcap_scaled_timeseriesdata <- prcomp(Mcap_timeseriesdata[c(10:16)], scale=TRUE, center=TRUE)`. 

![PCA-threephase](https://user-images.githubusercontent.com/37846759/109566188-87bc5980-7ab1-11eb-88fc-13b17bbc0b0a.png)

I'd like to separate them into 3 panels because if they are all overlaid on top of each other it looks something like this.. 

![PCA-timeseries](https://user-images.githubusercontent.com/37846759/109566622-1f21ac80-7ab2-11eb-856d-cd6bca8913ea.png)

**Comment by hputnam** [comment]
Extract PC values 
Try the following
pca <- prcomp(~ Temperature * CO2 * Time, data = USArrests, scale = TRUE, center=TRUE)

loadings <- pca$rotation

The plot the loadings for your points of interest for particular times or treatments

**Comment by emmastrand** [comment]
https://github.com/hgreich/ironXtemp/blob/master/Fig_3_S4_S5_METAL_calc_stats_figs.Rmd

**Comment by emmastrand** [comment]
turns out all I had to do was add facet_grid(~Phase) 

`mcap.three <- autoplot(Mcap_scaled_timeseriesdata, data = Mcap_timeseriesdata, colour = 'Treatment',
         loadings = TRUE, loadings.colour = 'black', frame=TRUE, size=0.5, frame.type = 'norm',
         loadings.label = TRUE, loadings.label.size = 3, loadings.label.colour = 'black', loadings.label.vjust=-1) + theme_bw() +
  theme(legend.position = "none") +
  facet_grid(~ Phase) + theme_bw() +
  scale_color_manual(values = cols) + scale_fill_manual(values = cols) + ggtitle("Montipora capitata"); mcap.three`

Mcap_scaled_timeseriesdata is the prcomp result. Mcap_timeseriesdata is my metadata frame.

**Comment by hputnam** [comment]
https://github.com/hputnam/Acclim_Dynamics/blob/master/Scripts/PCA_Plasticity.R
