### ISSUE TITLE
Creating publication-ready tables from any output in R

### ISSUE THREAD

**Issue by emmastrand** [Putnam-Lab/Lab_Management#15]
I have four separate PERMANOVA results outputs I'd like to put into one table in R and export it nicely. Thoughts?

Danielle had previous put this https://www.rdocumentation.org/packages/sjPlot/versions/2.8.6/topics/tab_model page into slack.

**Comment by daniellembecker** [comment]
Yes, the tab model function has always been helpful for me! You can also combine multiple output tables for it which is nice.

**Comment by daniellembecker** [comment]
I use it in this script, you can find the detailed code on line 578-594 if you wanna see :)

**Comment by emmastrand** [comment]
https://haozhu233.github.io/kableExtra/awesome_table_in_html.html
