### ISSUE TITLE
Connecting lines by factor (or variable) instead of x axis position

### ISSUE THREAD

**Issue by emmastrand** [Putnam-Lab/Lab_Management#16]
In the below plot I would like the lines to be connected by timepoint (Day 2 to 2 wk to 4 wk to 8 wk to 12 wk). Right now they are connected by the x axis position. How do I switch this? The P. acuta high temperature just happens to have the same x axis position as timepoint so it looks correct. 

![CSP-all](https://user-images.githubusercontent.com/37846759/111193433-877f8c00-8590-11eb-81ee-50815b180dca.png)

**Comment by daniellembecker** [comment]
I think this should be helpful: https://www.r-graph-gallery.com/connected-scatterplot.html

**Comment by daniellembecker** [comment]
https://www.r-graph-gallery.com/267-reorder-a-variable-in-ggplot2.html

I think the fct_relevel() function may be helpful because you can specify the order of your levels so probably would work for line connections.
