### ISSUE TITLE
Test New Lab Dissecting scopes

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#2]
* Label each scope
* use scale to take images and test quality (e.g., bulges in image at edge cause issue for size measurement)
* Summarize any issues or missing pieces by scope number
* check all light sources
* recommend best scope(s) for image analysis
* mark issues with tape

**Comment by kevinhwong1** [comment]
Is the phone on the microscope the "lab camera"? If so, what is the passcode?

**Comment by hputnam** [comment]
@kevinhwong1 can you confirm and summarize findings?

**Comment by kevinhwong1** [comment]
- Label each scope
**All scopes are labeled on the side MC #1-#3**
- Use scale to take images and test quality (e.g., bulges in image at edge cause issue for size measurement)
**MC#1 has a variance of 9%, MC #3 has a variance of %4**
- Summarize any issues or missing pieces by scope number
**We are missing one light, MC#1 needs a plexiglass bottom, MC#1 seems to have curved edges (hence the large variance), MC#2 is rusted and difficult to adjust height**
- Check all light sources
**We need one more light source**
- Recommend best scope(s) for image analysis
**MC#3!**
- Mark issues with tape

**Comment by hputnam** [comment]
Thanks @kevinhwong1
