### ISSUE TITLE
GitHub Notebooks: Avatar image works in GitHub "Notebook" tab, but not about "About and CV" tab

### ISSUE THREAD

**Issue by AHuffmyer** [Putnam-Lab/Lab_Management#25]
The image avatar shows up on my GitHub notebook main page (https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/), but not on any other notebook webpage (entries, CV, etc) (e.g., https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/about/). Has anyone experienced this problem?

**Comment by daniellembecker** [comment]
@AHuffmyer I did run into this issue, I edited the _configure.yml file as you did but I had to put my .png image with a GitHub link, see code below! 

`# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar

"https://raw.githubusercontent.com/daniellembecker/DanielleBecker_Lab_Notebook/master/images/Danielle_Becker.png"`

**Comment by AHuffmyer** [comment]
Thanks @daniellembecker! That solved the issue so that the avatar does stay when I navigate to category/date/tag view pages as well as post pages. Yay! But interestingly, it still is broken on the About/CV page - did you find you had to change the code for that page specifically elsewhere?

**Comment by daniellembecker** [comment]
Hmm so weird, I don't think you need to, I know that I had to change some things in the https://github.com/daniellembecker/DanielleBecker_Lab_Notebook/blob/master/_layouts/default.html so could see if that misaligns for some reason!

**Comment by AHuffmyer** [comment]
Thank you so much!
