### ISSUE TITLE
Update Physiology Protocols for Putnam Lab specific equipment

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#26]
Specifically, copy these to Putnam lab management repo and update them for local equipment 
[E5](https://github.com/urol-e5/protocols)

**Comment by hputnam** [comment]
move md protocol files from E5 and update as needed for URI equipment

**Comment by emmastrand** [comment]
These protocols have been copied and edited. Additional details would be helpful - like photos of our equipment in the Putnam Lab and any edits lab members have made to their samples (i.e. adult tissue vs eggs).

**Comment by hputnam** [comment]
@emmastrand can you keep this open and assign people to add specific equipment photos, etc??

**Comment by emmastrand** [comment]
Yes! I'll take photos of the equipment when I'm back in September since I'm not sure if anyone is actively using these protocols until then.

**Comment by hputnam** [comment]
@chloe-gilligan please finalize this by 30 April 2024.

**Comment by hputnam** [comment]
@chloe-gilligan are you still on track to finalize this for 30 April?

**Comment by chloe-gilligan** [comment]
@hputnam yes I am and will close issue when complete
