### ISSUE TITLE
Add photos and video to the titrator protocol

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#29]
https://github.com/Putnam-Lab/Lab_Management/blob/master/Lab_Resources/Equipment_Protocols/Titrator_Protocols/Titrator_Protocol.md

**Comment by daniellembecker** [comment]
Added: https://github.com/Putnam-Lab/Lab_Management/blob/master/Lab_Resources/Equipment_Protocols/Titrator_Protocols/Titrator_Protocol.md
