### ISSUE TITLE
Lab Inventory

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#31]
Inventory the following areas outlined in red: 
<img width="1001" alt="Screen Shot 2021-12-27 at 11 02 56 AM" src="https://user-images.githubusercontent.com/5198996/147488349-3ee21d7f-6f08-4b3e-9b54-fa8ffed59d56.png">

and make a QR code to link to the inventory spreadsheet: https://docs.google.com/spreadsheets/d/1_0Qe9gYnuqSAA0Lr24fjMHW3b2HDtKML87l29piD6uM/edit#gid=77700887. 

For example: https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=292366767

**Comment by hputnam** [comment]
@PierrickHarnay inventory and organize Red Storage Shelf (Putnam lab shelves only)

**Comment by hputnam** [comment]
@laurenzane inventory and organize wooden shelf by lab door next to large silver sink

**Comment by hputnam** [comment]
@JillAshey please inventory and organize the CBLS storage shelves

**Comment by hputnam** [comment]
[Lab Inventory](https://docs.google.com/spreadsheets/d/1_0Qe9gYnuqSAA0Lr24fjMHW3b2HDtKML87l29piD6uM/edit#gid=0)

**Comment by laurenzane** [comment]
Hi everyone! I organized the shelf area today and the drawer and took out a bunch of miscellaneous items. Please take a look and see where things can be rehomed.

**Comment by hputnam** [comment]
@laurenzane please post a picture of what does not fit there anymore and needs to be moved

**Comment by hputnam** [comment]
Letʻs set up a biannual update process for this along with updating it as best we can individually on a weekly basis.
