### ISSUE TITLE
Add ImageJ surface area extraction protocol

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#33]

**Comment by hputnam** [comment]
add the protocol to this folder please https://github.com/Putnam-Lab/Lab_Management/tree/master/Lab_Resources/Physiology_Protocols

**Comment by JillAshey** [comment]
updated protocol here: https://github.com/Putnam-Lab/Lab_Management/blob/master/Lab_Resources/Physiology_Protocols/ImageJ-Analysis-Protocols.md
