### ISSUE TITLE
Make helpful Moorea travel guide and requirements page for lab

### ISSUE THREAD

**Issue by daniellembecker** [Putnam-Lab/Lab_Management#35]
Hi all! I think it would be helpful to work together to make a useful protocol for Moorea planning with all of the numerous links, forms, planning that is necessary for it. It is in the early stages but if anyone is interested and can add helpful resources, advice, or guidance to it over the semester that would be amazing! Thank you! 

I plan to work on it while I go through the process this next month too but the more eyes on it the better :)

https://github.com/Putnam-Lab/Lab_Management/blob/master/Field_Resources/Field_and_Travel_Protocols/Moorea_Planning_Protocol.md

**Comment by AHuffmyer** [comment]
Sounds great! Happy to contribute.

**Comment by daniellembecker** [comment]
Thank you!

**Comment by hputnam** [comment]
@daniellembecker can you do this as you prep for this next trip?

**Comment by hputnam** [comment]
Please complete this by Sept 1

**Comment by hputnam** [comment]
[https://sites.google.com/view/moorearesponsiblefieldwork](https://urldefense.proofpoint.com/v2/url?u=https-3A__sites.google.com_view_moorearesponsiblefieldwork&d=DwMFaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=6vvIGXnw7HQ0elnOAqPM4w&m=h7byNo-pbx3PvXFC-LyFN4DvjfD8sICppt6dyUVHgoj3ifpL7-P4rHaVD8tkx482&s=g0a10OLp9ryjMJ3_a1bueFTkkBVBuHsX6E5qpoId_dE&e=)
