### ISSUE TITLE
Create a tutorial for QC and filtering of TagSeq/RNAseq analysis in Putnam Lab Management

### ISSUE THREAD

**Issue by AHuffmyer** [Putnam-Lab/Lab_Management#36]

**Comment by AHuffmyer** [comment]
I don't have a notebook post on QC. It would be a great group exercise if there are a few people with TagSeq datasets.

**Comment by AHuffmyer** [comment]
Who is the next to have a TagSeq dataset that we can use to create a tutorial?

**Comment by hputnam** [comment]
@flofields please work @AHuffmyer to complete this by 10 April 2024 as you presents on this topic and are working on your own dataset. @flofields creating this guide will ensure you understand your data and your QC choices.

**Comment by AHuffmyer** [comment]
@flofields I will have limited availability because I am preparing for travel to Australia starting April 8. Let me know if you would like to meet this week to talk about QC steps before I leave.

**Comment by AHuffmyer** [comment]
Great! Could we meet Friday at 10am Pacific/1pm Eastern?

**Comment by flofields** [comment]
works for me @AHuffmyer

**Comment by AHuffmyer** [comment]
Great! Could you please make a calendar invite/zoom link @flofields?
