### ISSUE TITLE
Apogee Instruments - Underwater Quantum Flux Meter Repair

### ISSUE THREAD

**Issue by daniellembecker** [Putnam-Lab/Lab_Management#37]
Problem with Underwater Quantum Flux Meter - When I was in Mo'orea in April 2022, I noticed that the Apogee Underwater Quantum Flux Meter (Model MQ-510; serial number 1214) was reading ~55 umol m-2 s-1 in complete darkness with the cap on. When I recently turned it on it was reading 0 with the cap on, but when I took the cap off, it was staying at ~1-2 which is still very off of the correct light value. I called technical support and they said there could be corrosion or something wrong with the board since this model and serial number was made in 2017 and has more issues over time. They said a repair and calibration would be ~$50 with shipping costs as it is out of warranty. I just need to fill out the repair form located [here](https://www.apogeeinstruments.com/recalibration-and-repairs/) and send it in.

**Comment by hputnam** [comment]
@daniellembecker Can you please get a quote for the repair and ask if we can pay by card or if we need to do a PO? Thank you!

**Comment by daniellembecker** [comment]
@hputnam will do!

**Comment by daniellembecker** [comment]
@hputnam still have yet to hear back, contacting them again for an update.

**Comment by daniellembecker** [comment]
@hputnam shipped the package on July 12, 2022, to Apogee Instruments for repair.

Tracking number
777360674930

Pickup confirmation number
PVDA-3147

**Comment by hputnam** [comment]
@daniellembecker can you check in with Apogee for an update?

**Comment by daniellembecker** [comment]
@hputnam yes, I will send an email

**Comment by daniellembecker** [comment]
Received an update on our Apogee meter on August 22:

"Hi Danielle,
 
Thank you for your patience regarding the repairs to your meter.  I have attached a quote on repairs to this email.  There is extensive corrosion on the internal circuit board especially around the battery cradle.  I have unfortunately been unable to recreate the micromole readings with the sensor capped.  My best bet is that there was perhaps some moisture that has since dried and so it is functioning accordingly.  But due to the circuit board corrosion,  it will need to be replaced.  The cost for a new board is $75 plus shipping.
 
Let me know if you have any further questions or concerns or if you would like us to go ahead with the repairs.  Have a great day!
 
Best regards,
 
Robin Gregerson"

Hollie paid for the repair and shipping on August 25th.
[Univ of Rhode IslandQuote.pdf](https://github.com/Putnam-Lab/Lab_Management/files/9427413/Univ.of.Rhode.IslandQuote.pdf)
![Uploading Screen Shot 2022-08-25 at 2.32.11 PM.png…]()

**Comment by hputnam** [comment]
Tracking for repaired Apogee - 

1Z78A7E60345060681

**Comment by JillAshey** [comment]
Apogee has been repaired and is on the brown bookshelf in the lab
