### ISSUE TITLE
Orion meter/probe broken

### ISSUE THREAD

**Issue by laurenzane** [Putnam-Lab/Lab_Management#38]
This week, I had noticed that the probe for the Orion meter would read "ready" and stabilize, but then quickly decline. After stirring, the reading would come back up to about the original reading but again, would decline. Additionally, the probe would measure the calibration fluid as about 46 psu, when it should read 50 psu.

1. Today, I turned on the Orion meter and it was frozen on the screen with a reading of 0.00psu; I could not calibrate nor measure salinity. 
2. I brought the Orion meter from the lab that we use for titrations but left its probe upstairs. I plugged in the aquarium probe and the same issue occurred with the calibration and measurement.

I will work on trying to fix these issues next week before submitting a broken equipment report.

**Comment by hputnam** [comment]
@laurenzane is this still an issue?

**Comment by laurenzane** [comment]
No, I will close it. The Orion probe is working as expected now with new calibration fluid.
