### ISSUE TITLE
Dry Shipper Losing Charge in 24 hours

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#41]

**Comment by hputnam** [comment]
original purchase information @JillAshey <Qte  201008_0747113 HPutnam shipper 10-8-2020.pdf>

**Comment by hputnam** [comment]
Customer Service Contact - https://www.thermofisher.com/us/en/home/technical-resources/contact-us.CY50910.html?supportType=SL

**Comment by JillAshey** [comment]
Case #: 04632650. 

Communicating with returns department, they will be sending a replacement shipper covered by our warranty. Our warranty on this shipper expires at the end of August.

**Comment by JillAshey** [comment]
New dry shipper (covered under warranty) arrived 8/10/22. 

Information about our case with ThermoFischer: 
WARRANTY- RA934349- PO 806163- STATE OF RHODE ISLAND MASTER- CASE 04632650 [ ref:_00D606yt2._5004z1g6EOB:ref ]

**Comment by JillAshey** [comment]
New shipper also appears to be broken. It doesn't hold a charge and a large amount of frost/condensation builds up on the lid and the sides. Called Tech Support and they are sending a technician out to look at it (date TBD, Jill will meet him). New case # is 4655429.

**Comment by hputnam** [comment]
Another New Shipper was sent. Jill Ashey requested a new one and tested it. It has held charge for at least 48hours.  @JillAshey please label this one as Shipper #2 and the original working one as Shipper #1 
@JillAshey please track the total time Shipper #2 holds a charge

**Comment by JillAshey** [comment]
All shippers are labeled. Working shippers are # 1 and # 2, defective shippers are # 3 and # 4.

**Comment by hputnam** [comment]
defective shippers # 3 and # 4 moved into CBLS 090 Field storage in case we need the transport cases or can fix the vacuum.
