### ISSUE TITLE
Presens OXY-10 ST (G2) USB cable issue

### ISSUE THREAD

**Issue by daniellembecker** [Putnam-Lab/Lab_Management#45]
In July 2022, Danielle Barnas noticed that when the OXY-10 USB connection cable was plugged into the laptop it was having issues. With even a slight bump to the table or movement of the OXY-10 or laptop, the USB cable would randomly disconnect during a run from the Presens Software/the OXY-10 itself (it would make the dinging noise indicating a loss of connection and reconnection with the computer over again). To mitigate issues with this, Danielle was very careful to never move the cable or anything once connected but this can cause unnecessary issues and disconnection during the run that will interrupt the date. 

I think we should order a new cable from Presens just to be safe as I checked on the cable when I arrived and it looks like there may be some corrosion just from continued use and wear and tear.  

@hputnam can you please confirm from the original order this is the OXY10 product we have in Mo'orea: [OXY-10 ST(G2)](https://www.presens.de/products/detail/oxy-10-st-g2). They now have multiple types so I want to confirm before we put in an order for the cable. Once you confirm, I can email Presens to get a quote and shipping time if needed.

Thanks!

**Comment by hputnam** [comment]
@daniellembecker Attached is the order information.
Check to see if this happens on multiple USB ports and multiple computers.
Take pictures of the ends of the cables.
Take Pictures of the cable port on the Presens.
Then please contact Presens to ask their thoughts on the problem with that information in hand.
[Quotation 2017-30300_Univ RI_OXY-10ST.pdf](https://github.com/Putnam-Lab/Lab_Management/files/9227056/Quotation.2017-30300_Univ.RI_OXY-10ST.pdf)

**Comment by daniellembecker** [comment]
@hputnam the cable has been checked on multiple computers (Danielle's, Hendrikje's, and the Putnam surface) all having the same issue. I have taken the photos and will contact Presens with this information. Thank you!

**Comment by hputnam** [comment]
Cable and Unit Photos 20220730

![IMG_8173](https://user-images.githubusercontent.com/5198996/182026065-478d6484-4da8-4b8d-b295-8020279efc29.jpg)
![IMG_8172](https://user-images.githubusercontent.com/5198996/182026066-6d681633-c3d3-440f-a165-d77434e7e138.jpg)
![IMG_8174](https://user-images.githubusercontent.com/5198996/182026069-010ed6cf-5cbe-4f61-be41-f5da951a8c6b.jpg)
![IMG_8176](https://user-images.githubusercontent.com/5198996/182026070-e5490002-e3b5-439d-91ff-9bcb648c74a4.jpg)
![IMG_8175](https://user-images.githubusercontent.com/5198996/182026072-d9b297cd-48fe-4122-8773-8c2fcafcbe3e.jpg)

**Comment by daniellembecker** [comment]
@hputnam PreSens recommended sending in the OXY-10 in for service but I explained how it is in a remote area so I figured that would not be an option at the moment so they responded with:

Hi Danielle,
 
Then we would recommend you to try it purchasing a new USB-cable.
The fastest way for you would be if you purchase the cable directly.
Below you can find some information of the USB-cable we use:
USB Cable, Type A Plug to Type B Plug, 3 m, 9.8 ft, USB 3.0, Black
Manufacturer [VIDEK](https://urldefense.proofpoint.com/v2/url?u=https-3A__de.farnell.com_b_videk&d=DwMGaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=xyhh-msJeYELaE_21mBq4oPKJX2mnAZiUxYehep8nmU&m=Me3eDLDNIkfIlgLCpY9t8v4r_oDIYZNWdgMqVMDUaQhNJcVTmFtIGeIrFjhiorKA&s=_3DfgA4vQSU9W5fSfVSuoXTpH0rFa_e8XXnVEtIGnMI&e=)
Manufacturer part number: 2585A-3
[https://de.farnell.com/en-DE/videk/2585a-3/kabel-usb-3-0-a-to-b-highspeed/dp/2082903](https://urldefense.proofpoint.com/v2/url?u=https-3A__de.farnell.com_en-2DDE_videk_2585a-2D3_kabel-2Dusb-2D3-2D0-2Da-2Dto-2Db-2Dhighspeed_dp_2082903&d=DwMGaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=xyhh-msJeYELaE_21mBq4oPKJX2mnAZiUxYehep8nmU&m=Me3eDLDNIkfIlgLCpY9t8v4r_oDIYZNWdgMqVMDUaQhNJcVTmFtIGeIrFjhiorKA&s=ow3F25cgrG-cZtdu5f06brKTTbStskfsfQqGYHyczBc&e=)
 
We hope this helps you, Danielle!
 
Best regards,
Anna

**Comment by daniellembecker** [comment]
8/30 - 5 replacement cables for the OXY10 - computer connection arrived. Hollie put one on the To Moorea pile and 4 on the wooden bookshelf by the door
