### ISSUE TITLE
Add protocol for submitting travel authorization requests and travel expense reports to the Wiki

### ISSUE THREAD

**Issue by AHuffmyer** [Putnam-Lab/Lab_Management#46]
Update and add detailed information on TAR and TER's here: https://github.com/Putnam-Lab/Lab_Management/wiki/Travel-Information

**Comment by daniellembecker** [comment]
Completed detailed information for submitting TAR and TER's on our [wiki travel information page](https://github.com/Putnam-Lab/Lab_Management/wiki/Travel-Information). Feel free to edit or add anything!
