### ISSUE TITLE
SRA and Genbank uploads for all sequence data

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#47]

**Comment by hputnam** [comment]
https://docs.google.com/spreadsheets/d/1qDGGpLFcmoO-fIFOPSUhPcxi4ErXIq2PkQbxvCCzI40/edit#gid=0

**Comment by hputnam** [comment]
https://github.com/Putnam-Lab/Lab_Management/tree/master/Bioinformatics_%26_Coding/Data_Mangament

**Comment by AHuffmyer** [comment]
Confirmed Mcap2020 ITS2, 16S, and TagSeq sequences uploaded to SRA with metadata added to our lab sequencing inventory. Project PRJNA900235

**Comment by AHuffmyer** [comment]
We need to revisit this spreadsheet at a lab meeting to go over the format of metadata and update all projects. https://docs.google.com/spreadsheets/d/1qDGGpLFcmoO-fIFOPSUhPcxi4ErXIq2PkQbxvCCzI40/edit#gid=0

**Comment by hputnam** [comment]
please confirm here in a comment that every sequencing dataset you worked with is listed on this file: https://docs.google.com/spreadsheets/d/1qDGGpLFcmoO-fIFOPSUhPcxi4ErXIq2PkQbxvCCzI40/edit#gid=0

@daniellembecker 
@flofields 
@zdellaert 
@JillAshey 
@AHuffmyer 
@PierrickHarnay 
@hputnam

**Comment by AHuffmyer** [comment]
Confirmed all my sequencing data that is in hand is accounted for on this sheet. Are E5 sequencing projects documented elsewhere?

**Comment by zdellaert** [comment]
Confirmed Pdam Heron Island pCO2

**Comment by daniellembecker** [comment]
Confirmed 20231214_Apulchra_RiboDepletion

**Comment by AHuffmyer** [comment]
Confirmed all files are updated with Andromeda backup location
