### ISSUE TITLE
Problems with connecting the edited repository to the online git notebook

### ISSUE THREAD

**Issue by kevinhwong1** [Putnam-Lab/Lab_Management#5]
- git push origin master ## updating changed files to the git repository
- git status ## ensure that files are synced
The following link "https://kevinhwong1.github.io/KevinHWong_Notebook" does not work
--> Error 404 
- Checked manually on the online repository and the changes are present

Problem: how to make the link (web page) active from a forked repository

**Comment by hputnam** [comment]
Please describe the problems in a reproducible way so that we can trouble shoot. For example, include a description of what commands are you running and what works or doesn't.,

**Comment by hputnam** [comment]
try editing your baseurl as follows in the _config.yml file

baseurl: ""

Check out https://github.com/Putnam-Lab/putnam-lab.github.io/blob/master/_config.yml for successful fork of my lab notebook with website https://putnam-lab.github.io/

**Comment by hputnam** [comment]
After config is changed, you need to go into settings on github repo online page and activate master branch as website.
