### ISSUE TITLE
Setup a log of Unity and Andromeda Reference and Database updates

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#53]
Set up a google form for the dates and locations of updates to Unity and Andromeda reference and database files (e.g., NCBI nr, Genomes, etc)

**Comment by hputnam** [comment]
make a list in text file in the REFERENCES shared file of all of the references we most commonly use (swiss prot, NCBI nr etc) and then add a line of date whenever we update them.

**Comment by AHuffmyer** [comment]
Update to databases: We contacted Kevin Bryan to update permissions because some people were not able to build the databases on Andromeda. @daniellembecker what was the resolution to this problem?

**Comment by AHuffmyer** [comment]
The most reliable way to keep track of dates may be to rename the database files with the current date. File information will then contain the date generated and who generated the database.
