### ISSUE TITLE
GPS GARMIN Mo'orea field work 

### ISSUE THREAD

**Issue by PierrickHarnay** [Putnam-Lab/Lab_Management#54]
It would be necessary to send the Garmin GPS used for the ground in repair because impossibility of recovering the data due to the corrosion located at the entry of the cable of connection. 
Thank you in advance!

**Comment by hputnam** [comment]
@chloe-gilligan Please call Garmin this week and check on how we can recover data for the 2 yellow GPS units from Moorea and if they can repair them. https://support.garmin.com/en-US/ They are currently in my office.

**Comment by hputnam** [comment]
Hi Hollie,

For the Garmin GPS, they were not able to offer a replacement as the model does not exist anymore. He was not able to offer their new model as a replacement but I was able to get their new model down from ~$400 to $239.99 for each. If you would like to replace them both I can complete the order form.




Best,
Chloé

**Comment by hputnam** [comment]
@chloe-gilligan If that is the case, I would just like the data extracted from the units. Is Garmin able to do that?

**Comment by hputnam** [comment]
Hollie extracted the data from both garmins using the garmin cable and treated them like external harddrives and downloaded the data to her computer.  These units are available for use and in working order.
