### ISSUE TITLE
Add more courses to "Recommended Courses" section in Current Student Resources page

### ISSUE THREAD

**Issue by zdellaert** [Putnam-Lab/Lab_Management#56]
Hi all current grad students, I added a "Recommended Courses" section to the current student resources, please add in the course name, number, instructor, number of credits, and a course description to any classes you think other Putnam lab students would benefit from!

[Page is here!](https://github.com/Putnam-Lab/Lab_Management/wiki/Current-Student-Resources#Recommended_Courses)

**Comment by emmastrand** [comment]
Added my favorites! I don't know the update name of Jon's class though. I made a note next to it that the title of the class might be different now.

**Comment by daniellembecker** [comment]
Thank you for organizing this @zdellaert! I just added some of my favorites and course descriptions to some others. I couldn't find the syllabus/description for Jon's class, @JillAshey and I took it so she may have them :)
