### ISSUE TITLE
Lab Notebook Database

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#6]
make a md file for our lab notebook database

**Comment by hputnam** [comment]
@kevinhwong1 can you give an update on this? We will need a md file with lab number, personnel, general project contents, start date, end date, electronic archival file name and location.

**Comment by kevinhwong1** [comment]
Please refer to: 
https://github.com/Putnam-Lab/Lab_Management/blob/master/Laboratory_Notebooks/Notebook_database.md

**Comment by hputnam** [comment]
@kevinhwong1 can you please fix this link

**Comment by kevinhwong1** [comment]
fixed! 

https://github.com/Putnam-Lab/Lab_Management/blob/master/Lab_Resourses/Laboratory_Notebooks/Notebook_database.md
