### ISSUE TITLE
RNA bench Vortex with tube attachment stopped working

### ISSUE THREAD

**Issue by zdellaert** [Putnam-Lab/Lab_Management#61]
Just want to note that we have already solved this by swapping it out with an unused vortex. Kristina and I found another tube-holder attachment in a drawer under the Qubit (look there for more vortex attachments and manuals!), so we are all set with this. However, the original one (["BenchMixer" from Benchmark scientific](https://www.benchmarkscientific.com/product/bv1005/)) is still broken. I called the company that makes them and they would provide no information about fixing it, but said they would be able to provide more information if I could provide the original PO.

**Comment by hputnam** [comment]
The vortex motor is no longer working. The options are for Hollie to try a fix, for the company to try to fix, or buy a new one ~$300
