### ISSUE TITLE
Update Lab Notebook Database

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#65]
https://github.com/Putnam-Lab/Lab_Management/blob/master/Lab_Resources/Laboratory_Notebooks/Notebook_database.md

**Comment by AHuffmyer** [comment]
What is the ideal format for this? Do we want one link for each person's notebook and a list of projects it contains? Depending on how people organize their tags and categories in the notebook it might not be possible to have a specific link that takes you to entries for each project.

**Comment by hputnam** [comment]
This is just for the physical lab notebooks that each have a number, not electronic lab notebooks. I am just looking for the main project name and funder and the time frame the physical notebook covers. We should also figure out a way to scan of photograph the whole physical notebook for electronic storage as we have done for E5.

**Comment by hputnam** [comment]
@AHuffmyer @emmastrand @daniellembecker @zdellaert @kevinhwong1 @flofields @JillAshey @chloe-gilligan @laurenzane  please update this database with your notebook numbers and links by 5 april 2024. https://github.com/Putnam-Lab/Lab_Management/blob/master/Lab_Resources/Laboratory_Notebooks/Notebook_database.md

**Comment by daniellembecker** [comment]
Done. Updated links to electronic storage for notebook pages that were scanned and uploaded to Google Drive folders. I have three main notebooks, numbers 27, 39, and 40.

**Comment by hputnam** [comment]
@daniellembecker please rename any file names as page numbers.

**Comment by emmastrand** [comment]
Hey all - I won't have access to my physical lab notebooks before April 5th so if this needed prior to Friday, then someone else is welcome to complete mine. Otherwise, I will likely be in Rhode Island April 18-19th and help then.

**Comment by AHuffmyer** [comment]
Updated all of my notebooks and links to electronic storage

**Comment by chloe-gilligan** [comment]
Updated all of my personal notebooks, 30, 51, 58 as well as the CBLS wetlab notebook 38

**Comment by laurenzane** [comment]
I'm all set as well!

**Comment by chloe-gilligan** [comment]
@hputnam Remaining lab notebooks were photographed, uploaded, and pages were numbered to the google drive folder and the lab notebook database
