### ISSUE TITLE
Freezer clean out of old samples

### ISSUE THREAD

**Issue by JillAshey** [Putnam-Lab/Lab_Management#70]
Zoe and I have been organizing and inventorying the -80C Putnam freezers over the past few weeks. We have completed J and K, and are almost done with Freezer G. After we are done with Freezer G, we will move the samples that are being stored in the Lane/Jenkins freezers to our own. 

We have found a lot of samples that are either not being actively used or the projects associated with those samples have been completed. These samples are taking up the majority of the freezer space, and we need to decide what to keep and what to toss. 

[Here](https://docs.google.com/spreadsheets/d/1IMYmnNsN4D9cFbgLVdGKz67Albb3LxEyBh2GMtREMPU/edit#gid=2141493053) is the cold storage inventory sheet. Please look at tabs G_Ultracold (-80°C), Currently_Upstairs_J_Ultracold (-80°C), NEW_J_Ultracold (-80°C), and NEW_K_Ultracold (-80°C), and write in the notes if these samples should be kept, moved to -20C, or discarded. Include initials and date when you make these notes. 

I'm going to assign @kevinhwong1, @emmastrand, @SamGurr, and @hputnam as they are the people with the most stuff in the freezers at the moment. This is an ongoing lab issue that we will need to revisit as more samples are generated and processed.

**Comment by emmastrand** [comment]
Thank you both for all the time you've put into this! I've made notes on all samples that have my name attached to them. These fell into three categories: 1.) Keep for longer term storage or until manuscript is published, 2.) I need to discuss with Hollie if we need to keep or not, and 3.) I can deal with improving labeling or throwing out when I'm back in Rhody next.

The tab that says 'Temp - Emma items' can probably be archived or deleted if you all are comfortable with that. Those notes are represented in the ones I made today and items I threw out a couple months ago.

I will be down in Rhode Island on Friday, March 1st and can stop by the lab to at least address the samples that fall into category #3. For most of the entries the note is longer term storage (or at least until ms is published) of fragments, DNA, RNA, tissue homogenate. I hear ya on need for more storage space though! It's the category #1 samples that take up the most room and make freezer space tricky with the growing projects the lab has.

At the end of the day, I feel like it's Hollie's call for what to keep or not to alleviate freezer space, but I will do my best to facilitate discussions around samples from the projects I was a part of. I appreciate you keeping me in the loop!


Best,

Emma Strand, Ph.D. (she/hers)

Postdoctoral Scientist


Gloucester Marine Genomics Institute Inc.<http://www.gmgi.org/>

417 Main Street, Gloucester MA

O: 978-879-4575


[cid:c7b09617-cb92-4823-91ca-4b13f76089bc]

________________________________
From: Jill Ashey ***@***.***>
Sent: Wednesday, February 7, 2024 8:30 AM
To: Putnam-Lab/Lab_Management ***@***.***>
Cc: Emma Strand ***@***.***>; Mention ***@***.***>
Subject: [Putnam-Lab/Lab_Management] Freezer inventory / clean out (Issue #70)


Zoe and I have been organizing and inventorying the -80C Putnam freezers over the past few weeks. We have completed J and K, and are almost done with Freezer G. After we are done with Freezer G, we will move the samples that are being stored in the Lane/Jenkins freezers to our own.

We have found a lot of samples that are either not being actively used or the projects associated with those samples have been completed. These samples are taking up the majority of the freezer space, and we need to decide what to keep and what to toss.

Here<https://url2.mailanyone.net/scanner?m=1rXi0i-0006I6-4T&d=4%7Cmail%2F90%2F1707312600%2F1rXi0i-0006I6-4T%7Cin2n%7C57e1b682%7C28509242%7C14152682%7C65C386044B83788499F54DBD69C8E7AB&o=%2Fphtr%3A%2Futsefldpns.eenfro.oitopu%2Fcol2%2Frmvsh%3Fu3tp-%3Dt.dA_ocsg_omeogsco_l.eaprtsheedY_s_nIMmd1F4Nsg9cbND7GLVlz6AdKBLbb2Eyh3xURGMeMP_tEi-di-3gdt2913D014324Md53aDwF%26%3D0%3DQ%26RWzscdNEZOEYS4jnrd4Jhg%26%3D0unPzXu5C47jvQfjcICWLbJrOqNncyle0rZMzCT0Immm_ojMkQ%26%3DZiknzQhlmVBQK27M9vyL-AhgpB2RftMgI6SZcMUqKrEwdM8N-uR9xn%26MOCbylXs%3DwF67OS-1btFozU0_nzD_aR_vEtpfpdzkPmr3%3De%26UtACK&s=mQtusWeNqy0vWROcrH34YpqzfVg> is the cold storage inventory sheet. Please look at tabs G_Ultracold (-80°C), Currently_Upstairs_J_Ultracold (-80°C), NEW_J_Ultracold (-80°C), and NEW_K_Ultracold (-80°C), and write in the notes if these samples should be kept, moved to -20C, or discarded. Include initials and date when you make these notes.

I'm going to assign @kevinhwong1<https://url2.mailanyone.net/scanner?m=1rXi0i-0006I6-4T&d=4%7Cmail%2F90%2F1707312600%2F1rXi0i-0006I6-4T%7Cin2n%7C57e1b682%7C28509242%7C14152682%7C65C386044B83788499F54DBD69C8E7AB&o=%2Fphtr%3A%2Futsefldpns.eenfro.oitopu%2Fcol2%2Frmvsh%3Fu3tp-%3DtugA_.thb_ii_cohevnmk%3Dgwow%26dDn1dQMFzc%3DWa%26nZ0sSjEYROu4N4%260dgEJjzr%3DC7P5hXbfn4CLQIujeOvWclrncqmZJyTIrCNM%3D_00k%26mMzoVkmQhmiQjnLKZl9yQMz2thBv2fAB7gqI-RcUgZp6uEMM8-rMSwyxKNOb9Mdn4sRCdyLA%26%3DygzJ5nte-A_lPdWBkZpfNfuydNNO1xYMwGe5W%26V5%3D&s=cv_E5mYQiGkNb94nMbfHDTeCoRA>, @emmastrand<https://url2.mailanyone.net/scanner?m=1rXi0i-0006I6-4T&d=4%7Cmail%2F90%2F1707312600%2F1rXi0i-0006I6-4T%7Cin2n%7C57e1b682%7C28509242%7C14152682%7C65C386044B83788499F54DBD69C8E7AB&o=%2Fphtr%3A%2Futsefldpns.eenfro.oitopu%2Fcol2%2Frmvsh%3Fu3tp-%3DtugA_.thb_ia_cotmmsmeDdraMd%3Dwn%26W%26Fa0%3DdzQcYOsRNEnSZjgJ4Erdu%26405X%3DhnPjCz7Ij4uvQbCfLnqWcJrecOlCMyN0rmTZIMo0zmm%3Dk_%26QnQjZiVhkmM2lzBQL9KyBgv7-At2hfZ6RpMgqcIUMwMSKru8E-MnNdR9yOxb6%3DC%26lyT8saGZPP2BuAJe_Y2uQYtuq4w1YoMSA31W%26l6y%3DvEeZ0&s=c8DIcnIo8YWUCxWo3PgfZKnT2c4>, @SamGurr<https://url2.mailanyone.net/scanner?m=1rXi0i-0006I6-4T&d=4%7Cmail%2F90%2F1707312600%2F1rXi0i-0006I6-4T%7Cin2n%7C57e1b682%7C28509242%7C14152682%7C65C386044B83788499F54DBD69C8E7AB&o=%2Fphtr%3A%2Futsefldpns.eenfro.oitopu%2Fcol2%2Frmvsh%3Fu3tp-%3DtugA_.thb_iG_coramumSF%3Dr%26QwMadDsd%26cZz0R%3DW4nOj4SNEEY%3DuJ0z%26rhdg4jX7fCnuP5WbjLOCvcQIyeqlZcJNrn0mMI_T0zrCQ%3Do%26kkmjmMlVnmKhZziQvL2yh9B7QMRtgfI2-pABMq6UEcMSgZNuw-x8KdrMCynbsOR%269MWT%3DYA1SZe5T8xbdCrVztUfH2WWVEFVo1ytPo9zH6%3De%26wpg1&s=B4Jo_ytjUe5PaESSenyWnhlXPIY>, and @hputnam<https://url2.mailanyone.net/scanner?m=1rXi0i-0006I6-4T&d=4%7Cmail%2F90%2F1707312600%2F1rXi0i-0006I6-4T%7Cin2n%7C57e1b682%7C28509242%7C14152682%7C65C386044B83788499F54DBD69C8E7AB&o=%2Fphtr%3A%2Futsefldpns.eenfro.oitopu%2Fcol2%2Frmvsh%3Fu3tp-%3DtugA_.thb_it_coapunmhF%3Dm%26QwMadDsd%26cZz0R%3DW4nOj4SNEEY%3DuJ0z%26rhdg4jX7fCnuP5WbjLOCvcQIyeqlZcJNrn0mMI_T0zrCQ%3Do%26kkmjmMlVnmKhZziQvL2yh9B7QMRtgfI2-pABMq6UEcMSgZNuw-x8KdrMCynbsOR%269MmS%3Dbzcs5cUoFtVx1Qb1ldXyykDaiX3X4og6QGTf7%3De%26Yt28&s=W6ou_exZ4Ks8-A4AgQOfJVcpjE0> as they are the people with the most stuff in the freezers at the moment. This is an ongoing lab issue that we will need to revisit as more samples are generated and processed.

**Comment by hputnam** [comment]
@hputnam check -20 chest freezer inventory and 50ml tubes and update as I remove the tubes from SG, ES, and HMP.

@kevinhwong1 you have several bags of 50ml tubes in the -80. Do you need these?

@kevinhwong1 and @emmastrand many whirlpaks of samples remain. What all should we keep?

**Comment by hputnam** [comment]
@hputnam send pictures to PPP and Kev and Emma and Sam as needed to clear out unlabeled items
