### ISSUE TITLE
Check capacity and fill test for dry shipper at URI

### ISSUE THREAD

**Issue by AHuffmyer** [Putnam-Lab/Lab_Management#71]
Hi Jill! When you have time, could you please let me know what size of dry shippers we have available at URI? I will be needing to transport samples from URI in prep for my Australia trip. I have 2-3 tube boxes that will need to be transported. Do we have a small/medium dry shipper that could fit a couple boxes? 

If so, could you please do a test fill to make sure it holds temperature as expected?

**Comment by AHuffmyer** [comment]
Will need enough capacity for ~150 tubes

**Comment by AHuffmyer** [comment]
@JillAshey please post any updates here!

**Comment by AHuffmyer** [comment]
Dry shipper filled at 10:30 by AH and HP, AH will monitor the rest of the day

**Comment by JillAshey** [comment]
Dry shipper still cold and filled with LN2 at 13:15

**Comment by hputnam** [comment]
Dry shipper still cold when Ariana charged it to travel. @AHuffmyer can you check it daily until Sam fills it to see how long it last from the time we emptied all liquid yesterday 3/30/24?

**Comment by AHuffmyer** [comment]
I will not be able to check the shipper before I leave for Australia because I cannot be on UW campus this week. I will monitor the shipper after I get to Australia to document how long it remains cold after being charged and will post updates here!

**Comment by hputnam** [comment]
Ariana was able to get this filled and transported to Australia. We will need to do another check in the lab of total time it holds LN2 after it is back

**Comment by AHuffmyer** [comment]
I will check daily while here in Australia and will be able to get a time range that it hold LN2 while I am here. Completed charge on April 8th at 08:00 Pacific Time.

**Comment by AHuffmyer** [comment]
Dry shipper still cold on April 17 @ 8:30am Australia Time (8 days since fill). 

Note that max capacity for tubes in a mesh bag, carefully packed to maximize space = ~130 tubes.

**Comment by AHuffmyer** [comment]
Dry shipper STILL cold at 16:30 on April 24 Australia Time. 

Currently at 15 days after fill.
