### ISSUE TITLE
Work with Oliver Palmer to get the silver biosafety cabinet out of our area in CBLS wetlab and set up storage for us there

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#74]
Please ask Oliver what we need to go to get the biosafety cabinet donated to URI community and moved out of CBLS wetlab.

**Comment by hputnam** [comment]
@chloe-gilligan I ordered a shelving unit that will arrive the end of next week. Can you please check in with Oliver on the timeline once per week until the biosafety cabinet is removed?

**Comment by hputnam** [comment]
@chloe-gilligan can you please check Monday that all of our equipment is moved away from the biosafety cabinet (i.e., nothing on, in, or under the biosafety cabinet)?

**Comment by chloe-gilligan** [comment]
@hputnam Everything is moved off and I will be following up with Oliver today!

**Comment by hputnam** [comment]
@chloe-gilligan thank you. The biosafety cabinet was removed as of 4/22/24.
