### ISSUE TITLE
Move Astrangia samples into long term storage

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#76]
move decalcified samples from formalin to ethanol in 2ml or smaller tubes and store in flammable cabinet

**Comment by hputnam** [comment]
Thank you @chloe-gilligan 

Let's hold the TP8 and high frequency samples as is right now until we finish the Astrangia paper.

Please contact Katie and Ben to see if they need their samples. If they don't submit them for waste.

Can you please update the inventory to reflect this?

**Comment by chloe-gilligan** [comment]
Sounds good, email has been sent and will update when I hear back.

**Comment by hputnam** [comment]
@JillAshey please discard the Barott Lab samples as required by URI.

**Comment by hputnam** [comment]
@JillAshey can you please work with or ask Lauren to move all of the samples from the fridge by the fume hood to the flammable fridge or to Kelton's lab as needed?

**Comment by hputnam** [comment]
@chloe-gilligan can you please schedule a pickup for all of the solid waste in the satellite accumulation area in the back hood?

**Comment by chloe-gilligan** [comment]
@hputnam Yes will do today!

**Comment by chloe-gilligan** [comment]
Hazardous waste forms have been submitted and waste is ready for pick up.
