### ISSUE TITLE
Pestle of large mortar & pestle broke

### ISSUE THREAD

**Issue by zdellaert** [Putnam-Lab/Lab_Management#77]
Hi all, unfortunately I was cleaning the pestle of the large mortar and pestle and it rolled off the counter and broke. I think it is still okay to use, especially with the latex palm gloves, but does anyone have ideas for gluing this type of porcelain? Superglue? I can also put in an order request for a new one if we don't trust a glued pestle.

![IMG_3649](https://github.com/Putnam-Lab/Lab_Management/assets/60702972/d628051d-3f82-4fce-9c2f-d35664f8d97a)

**Comment by hputnam** [comment]
@zdellaert can you please indicate the catalog number from fisher where we can order a replacement? This one can be put in the broken glass trash. Thank you!
