### ISSUE TITLE
Generate a generalized Permit Reporting Form - Deadline 20 May 2024

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#82]
Generate a standardize form and location for photos for each permit in the Lab google drive.

minimum information: date, species, life stage, number, size, GPS, collector

**Comment by AHuffmyer** [comment]
First draft of generalized form here: https://docs.google.com/forms/d/1cH55Quh9aLAwmv0FhhKoOQSc1Lmk10djtWe1ALnSuuo/edit 

Should I add or change anything?

**Comment by AHuffmyer** [comment]
Generalized form ready here: https://docs.google.com/forms/d/1cH55Quh9aLAwmv0FhhKoOQSc1Lmk10djtWe1ALnSuuo/edit

This can be revised to change locations or add other information.
