### ISSUE TITLE
Report collection table for Moorea 2023 field season to DIREN

### ISSUE THREAD

**Issue by AHuffmyer** [Putnam-Lab/Lab_Management#85]
Permit here: https://drive.google.com/drive/u/2/folders/1wUhYxVlvMOfFriEhnB-udNIVcX8fOhY5

**Comment by AHuffmyer** [comment]
Permit number (report on publications/presentations): ARRETEN® 4 06 26 /VP/DIREN du 06 NOV. 2023

**Comment by hputnam** [comment]
Submitted to Maheata on 8/22/24 - https://docs.google.com/document/d/1I3g-BvzZ0Ajvm_POFSL7zmDIXbaxKcAJuZln9HV1Q_g/edit
