### ISSUE TITLE
StringTie count matrices from GTF files: update to prepDE.py script!

### ISSUE THREAD

**Issue by daniellembecker** [Putnam-Lab/Lab_Management#87]
Recently found out that there is a new prepDE.py script when you need to generate gene and transcript count matrices from a set of GTF files produced by StringTie:

Moving forward, use the [prepDE.py3 script ](https://github.com/gpertea/stringtie/blob/master/prepDE.py3), which you can load into your directory using "wget https://raw.githubusercontent.com/gpertea/stringtie/master/prepDE.py3".

I also added it to our shared scripts directory in the Andromeda putnamlab folder: cd /data/putnamlab/shared/scripts/

**Comment by JillAshey** [comment]
what's the difference between the two?

**Comment by daniellembecker** [comment]
its a syntax difference between running python2 and python3, some differences were for the print statements, needed to have parentheses around them and other syntax changes when using the updated Python/3.9.6-GCCcore-11.2.0 module

**Comment by hputnam** [comment]
You should be able to use either one with the same results. One is based on python version 3 and named as such. In my understanding, this should not cause differences in the count matrix itself

**Comment by daniellembecker** [comment]
sounds good, I was getting syntax errors consistently in my slurm outputs and couldn't run the original prepDE.py script with the updated module but yes I don't think it would cause difference in the count matrix
