### ISSUE TITLE
Apex3 Pro Equipment Issues

### ISSUE THREAD

**Issue by daniellembecker** [Putnam-Lab/Lab_Management#88]
**Submitting service requests for multiple Neptune Systems Apex3 Pro equipment**

**1. Energy Bar 832 - 869269 
2. Energy Bar 832 - 27155
3. Energy Bar 832 - 118267**

Troubleshooting steps: When plugged in, none of them turn on even with a factory reset. I tried to reset and connect to the app, the reset makes a clicking noise but does not work, there are no indicator lights that come up which usually do after a factory reset. I also made sure it wasn't just because the indicator lights were out, I plugged in my computer charger to every outlet to see if any power was working with no luck. I also called Neptune Systems tech support where we tried all these steps and then they suggested we send out for replacement or repair.

**Apex3 Pro Apex Base Unit - 70324**

Troubleshooting steps: Continuously connected and disconnected over a few days. It would begin to cycle through colors, and then connect to Apex Fusion but after an hour or so it would disconnect again. It also seems to be causing issues to energy bars where if replaced and plugged in, would then over time not be able to use power. Tried multiple hard resets to factory settings, changed out multiple cables, found that one of the cable outlets was faulty so used the other but over time the issue continued to persist. Contacted support who suggested service or replacement.

**Comment by hputnam** [comment]
@daniellembecker Can you please update the status on this or comment and close?

**Comment by daniellembecker** [comment]
@hputnam I was recently in contact with Neptune systems about this and they gave us some various options for either service or replacement for this equipment. I wanted to wait till we met to confirm what options you preferred, as in, if the product is no longer available for service due to old parts, would you want a full replacement or not? I will have an itemized list for costs, etc. soon to run each option by you.

**Comment by hputnam** [comment]
Just provide the options they give us here and we can make a choice. Thanks.

**Comment by daniellembecker** [comment]
The EB832s with serial numbers 86269 and 118267 can be sent in for repair to our repair team. They will be able to diagnose them hands on and repair them. 
 
For the EB832 with serial number, 27155,  we no longer have the parts to repair that style of EB832, as we now have the InterTek listed EB832s. However, for being a loyal Neptune customer, we can offer you a one-time special discount price of $150 plus shipping for a new energy bar only (not in retail packaging). 
 
I can send you more information on how to send in the two for repair if you would like to proceed with that process. If you would like to proceed with the discounted EB832 as well, please let me know the following information and I can create that order and send you a payment link.

**Comment by daniellembecker** [comment]
Neptune Systems Apex products (three EB832s and an Apex Base Unit) sent out for repair: 778342910717

**Comment by daniellembecker** [comment]
Neptune systems apex products were returned after repair. 

Summary from Neptune systems repair:

The Apex NG required a new SD card installation and a firmware update ($50).
One of the EB832s required a replacement
PCB board ($75). The other EB832s were tested and received firmware updates.

Invoice paid for by @hputnam on November 28th 2024 and all products received December 6th 2024 and stored by @zdellaert
