### ISSUE TITLE
Loading and manipulating data from multiple Hobo Loggers

### ISSUE THREAD

**Issue by hputnam** [Putnam-Lab/Lab_Management#9]
@daniellembecker @emmastrand please move the answer to this here from slack.

**Comment by daniellembecker** [comment]
[HOBO.temp.R.docx](https://github.com/Putnam-Lab/Lab_Management/files/5857668/HOBO.temp.R.docx)

**Comment by daniellembecker** [comment]
From @emmastrand: suggestions on loading in and editing multiple CSV files at once? I have 12 hobo logger files I want to load and make the same edits to.

I’ve got hobo_files <- list.files("Environmental_data/Temp_Hobo_Loggers", pattern = "*.csv")  working but then trying to use read.csv and a for loop but getting stuck

**Comment by daniellembecker** [comment]
Code for combining HOBO logger data

[HOBO.temp.R.docx](https://github.com/Putnam-Lab/Lab_Management/files/5857673/HOBO.temp.R.docx)
