### ISSUE TITLE
Band Saw Motor Issues

### ISSUE THREAD

**Issue by zdellaert** [Putnam-Lab/Lab_Management#96]
The Inland band saw we are using downstairs in the wetlab is not functioning. I noticed last time I was using it that there was a small crack in one of the legs of the saw which was causing the saw to wobble back and forth quite a bit. Now, the saw will not turn on at all. I am not sure if somehow water got into the motor or if the off-balance wobbling caused a problem with the motor. I can contact the company sometime this week or next; do we have any information on where we ordered this (Bulk Reef Supply) and a receipt?

**Comment by zdellaert** [comment]
https://inlandcraft.com/pages/warranty/ - 90 day warranty when used in saltwater environments

**Comment by hputnam** [comment]
Thanks @zdellaert I have ordered a gryphon replacement. It should arrive the first week of December 2024
